version: "3"

services: 
    web:
        image: nginx:latest
        volumes:
            - ".:/root"
        ports:
            - "8883:80"
        environment:
            DEBUG: "true"
    
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
           MYSQL_ROOT_PASSWORD: randompassword
           MYSQL_DATABASE: wordpress
           MYSQL_USER: admin
           MYSQL_PASSWORD: admin
    
    cache:
        image: "redis:latest"
        ports:
            - "6379:6379"
