version: "3"

services: 
    web:
        image: nginx:latest
        volumes:
            - ".:/root"
        ports:
            - "8888:80"
        environment:
            DEBUG: "true"
    
    db:
        
        ports:
            - "3306:3306"
    
    cache:
        ports:
            - "6379:6379"
